export default {
  icon: {
    _num: "20",
    color: "p0",
    size: "p1",
    type: "p2",
  },
  "#text": {
    _num: "8",
  },
  ad: {
    _num: "9",
    adIntervals: "p0",
    unitId: "p1",
  },
  audio: {
    _num: "10",
    author: "p0",
    controls: "p1",
    id: "p2",
    loop: "p3",
    name: "p4",
    poster: "p5",
    src: "p6",
  },
  block: {
    _num: "11",
  },
  button: {
    _num: "12",
    disabled: "p0",
    formType: "p1",
    hoverClass: "p2",
    hoverStartTime: "p3",
    hoverStayTime: "p4",
    hoverStopPropagation: "p5",
    loading: "p6",
    name: "p7",
    openType: "p8",
    plain: "p9",
    size: "p10",
    type: "p11",
  },
  camera: {
    _num: "13",
    devicePosition: "p0",
    flash: "p1",
  },
  canvas: {
    _num: "14",
    canvasId: "p0",
    disableScroll: "p1",
  },
  "catch-view": {
    _num: "0",
    animation: "p0",
    hoverClass: "p1",
    hoverStartTime: "p2",
    hoverStayTime: "p3",
    hoverStopPropagation: "p4",
  },
  checkbox: {
    _num: "15",
    checked: "p0",
    color: "p1",
    disabled: "p2",
    name: "p3",
    value: "p4",
  },
  "checkbox-group": {
    _num: "16",
    name: "p0",
  },
  "cover-image": {
    _num: "17",
    src: "p0",
  },
  "cover-view": {
    _num: "18",
    scrollTop: "p0",
  },
  form: {
    _num: "19",
    name: "p0",
    reportSubmit: "p1",
  },
  image: {
    _num: "1",
    lazyLoad: "p0",
    mode: "p1",
    src: "p2",
  },
  input: {
    _num: "21",
    confirmHold: "p0",
    confirmType: "p1",
    cursor: "p2",
    cursorSpacing: "p3",
    disabled: "p4",
    maxlength: "p5",
    name: "p6",
    password: "p7",
    placeholder: "p8",
    placeholderClass: "p9",
    placeholderStyle: "p10",
    selectionEnd: "p11",
    selectionStart: "p12",
    type: "p13",
    value: "p14",
  },
  label: {
    _num: "22",
    for: "p0",
    name: "p1",
  },
  "live-player": {
    _num: "23",
    animation: "p0",
    autoplay: "p1",
    backgroundMute: "p2",
    maxCache: "p3",
    minCache: "p4",
    muted: "p5",
    objectFit: "p6",
    orientation: "p7",
    src: "p8",
  },
  map: {
    _num: "24",
    circles: "p0",
    controls: "p1",
    covers: "p2",
    includePoints: "p3",
    latitude: "p4",
    layerStyle: "p5",
    longitude: "p6",
    markers: "p7",
    polyline: "p8",
    scale: "p9",
    showLocation: "p10",
  },
  "movable-area": {
    _num: "25",
    scaleArea: "p0",
  },
  "movable-view": {
    _num: "26",
    animation: "p0",
    damping: "p1",
    direction: "p2",
    disabled: "p3",
    friction: "p4",
    height: "p5",
    inertia: "p6",
    outOfBounds: "p7",
    scale: "p8",
    scaleMax: "p9",
    scaleMin: "p10",
    scaleValue: "p11",
    width: "p12",
    x: "p13",
    y: "p14",
  },
  "native-slot": {
    _num: "27",
    name: "p0",
  },
  navigator: {
    _num: "28",
    delta: "p0",
    hoverClass: "p1",
    hoverStartTime: "p2",
    hoverStayTime: "p3",
    hoverStopPropagation: "p4",
    openType: "p5",
    url: "p6",
  },
  picker: {
    _num: "29",
    customItem: "p0",
    disabled: "p1",
    end: "p2",
    fields: "p3",
    mode: "p4",
    name: "p5",
    range: "p6",
    rangeKey: "p7",
    start: "p8",
    value: "p9",
  },
  "picker-view": {
    _num: "30",
    indicatorClass: "p0",
    indicatorStyle: "p1",
    maskClass: "p2",
    maskStyle: "p3",
    name: "p4",
    value: "p5",
  },
  "picker-view-column": {
    _num: "31",
    name: "p0",
  },
  progress: {
    _num: "32",
    active: "p0",
    activeMode: "p1",
    activeColor: "p2",
    backgroundColor: "p3",
    color: "p4",
    percent: "p5",
    showInfo: "p6",
    strokeWidth: "p7",
  },
  "pure-view": {
    _num: "2",
    animation: "p0",
    hoverClass: "p1",
    hoverStartTime: "p2",
    hoverStayTime: "p3",
    hoverStopPropagation: "p4",
  },
  radio: {
    _num: "33",
    checked: "p0",
    color: "p1",
    disabled: "p2",
    name: "p3",
    value: "p4",
  },
  "radio-group": {
    _num: "34",
    name: "p0",
  },
  "rich-text": {
    _num: "35",
    nodes: "p0",
  },
  "scroll-view": {
    _num: "36",
    animation: "p0",
    enableBackToTop: "p1",
    lowerThreshold: "p2",
    scrollIntoView: "p3",
    scrollLeft: "p4",
    scrollTop: "p5",
    scrollWithAnimation: "p6",
    scrollX: "p7",
    scrollY: "p8",
    upperThreshold: "p9",
  },
  slider: {
    _num: "37",
    activeColor: "p0",
    backgroundColor: "p1",
    blockColor: "p2",
    blockSize: "p3",
    disabled: "p4",
    max: "p5",
    min: "p6",
    name: "p7",
    showValue: "p8",
    step: "p9",
    value: "p10",
  },
  slot: {
    _num: "38",
    name: "p0",
  },
  "slot-view": {
    _num: "39",
    name: "p0",
  },
  "static-image": {
    _num: "3",
    lazyLoad: "p0",
    mode: "p1",
    src: "p2",
  },
  "static-text": {
    _num: "4",
    decode: "p0",
    selectable: "p1",
    space: "p2",
  },
  "static-view": {
    _num: "5",
    animation: "p0",
    hoverClass: "p1",
    hoverStartTime: "p2",
    hoverStayTime: "p3",
    hoverStopPropagation: "p4",
  },
  swiper: {
    _num: "40",
    autoplay: "p0",
    circular: "p1",
    current: "p2",
    displayMultipleItems: "p3",
    duration: "p4",
    indicatorActiveColor: "p5",
    indicatorColor: "p6",
    indicatorDots: "p7",
    interval: "p8",
    nextMargin: "p9",
    previousMargin: "p10",
    vertical: "p11",
  },
  "swiper-item": {
    _num: "41",
    itemId: "p0",
  },
  switch: {
    _num: "42",
    checked: "p0",
    color: "p1",
    disabled: "p2",
    name: "p3",
    type: "p4",
  },
  text: {
    _num: "6",
    decode: "p0",
    selectable: "p1",
    space: "p2",
  },
  textarea: {
    _num: "43",
    autoFocus: "p0",
    autoHeight: "p1",
    cursor: "p2",
    cursorSpacing: "p3",
    disabled: "p4",
    fixed: "p5",
    maxlength: "p6",
    name: "p7",
    placeholder: "p8",
    placeholderClass: "p9",
    placeholderStyle: "p10",
    selectionEnd: "p11",
    selectionStart: "p12",
    value: "p13",
  },
  video: {
    _num: "44",
    animation: "p0",
    autoplay: "p1",
    controls: "p2",
    danmuBtn: "p3",
    danmuList: "p4",
    direction: "p5",
    duration: "p6",
    enableDanmu: "p7",
    enableProgressGesture: "p8",
    initialTime: "p9",
    loop: "p10",
    muted: "p11",
    objectFit: "p12",
    pageGesture: "p13",
    poster: "p14",
    showCenterPlayBtn: "p15",
    showFullscreenBtn: "p16",
    showMuteBtn: "p17",
    showPlayBtn: "p18",
    showProgress: "p19",
    src: "p20",
  },
  view: {
    _num: "7",
    animation: "p0",
    hoverClass: "p1",
    hoverStartTime: "p2",
    hoverStayTime: "p3",
    hoverStopPropagation: "p4",
  },
  "web-view": {
    _num: "45",
    src: "p0",
  },
} as Record<string, Record<string, string | undefined> | undefined>;
